#!/usr/bin/env node
/**
 * `npm run voice:import`
 *
 * Parses the eight Chinese author voices from the pinned `ai-zixun/humanizer-zh` clone into
 * `.external-corpora/author-voices/author-voices.generated.json`.
 *
 * ## Why the artefact is not committed
 *
 * It was, until the release audit. The profiles are composed of prose about named living
 * writers, quoting their phrases and their books, and a public repository that ships them is
 * a repository that distributes eight named-author imitators. The upstream's MIT licence
 * covers the upstream's own compilation; it is not this project's to reason further about
 * whatever third-party quotations sit inside it, and the honest position is to distribute
 * none of it.
 *
 * So the capability stays and the text does not. Anyone who wants these voices clones the
 * upstream and runs this command; the output lands in `.external-corpora/`, which is
 * gitignored, and the plugin picks it up from there. `src/voice/import/demo-voice.json` is
 * committed instead — written for this repository, imitating nobody — so that the profile,
 * import and generation paths have something to run against on a fresh checkout.
 *
 * `--check` therefore verifies the local artefact only when it exists. A checkout without it
 * is a checkout that has not generated the upstream voices, which is the default state and
 * not a failure.
 */

import { writeFile, readFile } from 'node:fs/promises';
import path from 'node:path';

import { loadManifest, resolveProjectRoot } from '../../upstream/manifest.js';
import {
  AUTHOR_VOICE_FILES,
  VOICE_DIRECTORY,
  VOICE_UPSTREAM,
  countRemovals,
  importAuthorVoices,
} from '../import/index.js';
import { findHazards } from '../adaptation/index.js';
import type { VoiceImportReport } from '../import/index.js';

interface Options {
  readonly projectRoot: string;
  readonly out: string;
  readonly check: boolean;
  readonly quiet: boolean;
}

const DEFAULT_OUT = path.join('.external-corpora', 'author-voices', 'author-voices.generated.json');

function parseArgs(argv: readonly string[]): Options {
  const projectRoot = resolveProjectRoot();
  let out = path.join(projectRoot, DEFAULT_OUT);
  let check = false;
  let quiet = false;

  for (let index = 0; index < argv.length; index += 1) {
    const arg = argv[index];
    switch (arg) {
      case '--out': {
        const value = argv[index + 1];
        if (!value) throw new Error('--out requires a path');
        out = path.resolve(value);
        index += 1;
        break;
      }
      case '--check':
        check = true;
        break;
      case '-q':
      case '--quiet':
        quiet = true;
        break;
      case '-h':
      case '--help':
        process.stdout.write(
          [
            'Usage: npm run voice:import [options]',
            '',
            'Parses the eight author voices from the pinned upstream clone into a local file.',
            'The output is gitignored: this project does not distribute those profiles.',
            '',
            'Options:',
            '  --out FILE   Write to FILE instead of .external-corpora/author-voices/',
            '  --check      Do not write; if the local file exists, exit 1 when it is stale',
            '  -q, --quiet  Print only the summary',
            '  -h, --help   Show this help',
            '',
            'The upstream clone is read-only. Nothing is written to it.',
            '',
          ].join('\n'),
        );
        process.exit(0);
        break;
      default:
        if (arg !== undefined && arg.startsWith('-')) throw new Error(`Unknown option ${arg}`);
    }
  }

  return { projectRoot, out, check, quiet };
}

interface GeneratedFile {
  readonly generatedFrom: {
    readonly upstream: string;
    readonly revision: string;
    readonly licence: string;
    readonly directory: string;
    readonly files: readonly string[];
  };
  readonly profiles: VoiceImportReport['profiles'];
  readonly unmappedLabels: VoiceImportReport['unmappedLabels'];
  readonly removals: VoiceImportReport['harnessRemovals'];
  readonly note: string;
}

function render(report: VoiceImportReport, files: readonly string[]): string {
  const payload: GeneratedFile = {
    generatedFrom: {
      upstream: VOICE_UPSTREAM,
      revision: report.revision,
      licence: report.licence,
      directory: `${VOICE_DIRECTORY}/`,
      files,
    },
    profiles: report.profiles,
    unmappedLabels: report.unmappedLabels,
    removals: report.harnessRemovals,
    note:
      'Generated by `npm run voice:import`. Do not edit by hand: edit the parser in src/voice/import/index.ts. ' +
      'These are craft and habit profiles parsed from upstream prose. They carry no statistical features, because ' +
      'the upstream files contain no sample passages, and voiceScore therefore never compares against them.',
  };
  return `${JSON.stringify(payload, null, 2)}\n`;
}

async function main(): Promise<number> {
  const options = parseArgs(process.argv.slice(2));
  const manifest = await loadManifest(options.projectRoot);
  const entry = manifest.upstreams.find(
    (candidate) => `ai-zixun/${candidate.name}` === VOICE_UPSTREAM || candidate.name === 'humanizer-zh',
  );
  if (!entry) throw new Error(`${VOICE_UPSTREAM} is not in the upstream manifest`);

  // `--check` asks one question: is the generated artefact current? On a fresh checkout the answer
  // is "there is no artefact", which is the default state and not a failure — and it must be
  // answered *before* the upstream cache is touched, because a checkout that has never generated
  // the voices has no cache either. Reading the cache first turned the default state into a red
  // build on a clean clone, which is the one place this check was supposed to be green.
  if (options.check) {
    const existing = await readFile(options.out, 'utf8').catch(() => null);
    if (existing === null) {
      process.stdout.write(
        `${options.out} is not present. The author voices have not been generated locally, which is the ` +
          'default: this project does not distribute them. Run without --check to create them.\n',
      );
      return 0;
    }
  }

  const voiceDirectory = path.resolve(
    options.projectRoot,
    manifest.cacheDir,
    entry.name,
    VOICE_DIRECTORY,
  );

  let report: VoiceImportReport;
  try {
    report = importAuthorVoices({
      voiceDirectory,
      revision: entry.commit,
      licence: entry.license,
    });
  } catch (error) {
    process.stderr.write(
      `voice:import failed: ${String(error)}\n` +
        'The upstream cache is gitignored. Run `npm run upstream:check` to populate it.\n',
    );
    return 1;
  }

  const text = render(report, AUTHOR_VOICE_FILES.map((file) => file.file));

  if (options.check) {
    const existing = await readFile(options.out, 'utf8').catch(() => null);
    if (existing !== text) {
      process.stdout.write(
        `${options.out} is stale. Run npm run voice:import to regenerate it.\n`,
      );
      return 1;
    }
    process.stdout.write(`${options.out} is current.\n`);
    return 0;
  }

  await writeFile(options.out, text, 'utf8');

  if (!options.quiet) {
    process.stdout.write('Author voice import\n\n');
    process.stdout.write(`  upstream                   : ${VOICE_UPSTREAM} @ ${entry.commit.slice(0, 12)}\n`);
    process.stdout.write(`  licence                    : ${entry.license}\n`);
    process.stdout.write(`  profiles                   : ${report.profiles.length}\n`);

    let templates = 0;
    let rules = 0;
    let directives = 0;
    for (const profile of report.profiles) {
      templates += profile.writing?.rhetoricalDevices.length ?? 0;
      directives += profile.directives?.length ?? 0;
      rules += (profile.directives ?? []).filter((d) => d.startsWith('Voice rule:')).length;
    }
    process.stdout.write(`  sentence templates         : ${templates}\n`);
    process.stdout.write(`  voice rules                : ${rules}\n`);
    process.stdout.write(`  directives after cleaning  : ${directives}\n`);

    const unmapped = Object.entries(report.unmappedLabels);
    process.stdout.write(
      `  labels that did not map    : ${unmapped.reduce((total, [, list]) => total + list.length, 0)}` +
        (unmapped.length > 0 ? ` (${unmapped.map(([key, list]) => `${key}: ${list.length}`).join(', ')})` : '') +
        '\n',
    );

    for (const removal of report.harnessRemovals) {
      process.stdout.write(`  hazards removed at import  : ${removal.profile} (${removal.count})\n`);
    }

    // The two hazards the inventory flagged must be visible in the run output,
    // not merely handled in code: this is the line a reviewer looks for.
    for (const profile of report.profiles) {
      const remaining = findHazards(profile);
      const removed = countRemovals(profile);
      if (remaining.length > 0) {
        process.stdout.write(
          `\n  FAIL ${profile.id} still carries ${remaining.length} hazard(s): ` +
            `${remaining.map((hazard) => hazard.hazard).join(', ')}\n`,
        );
      }
      if (removed > 0 && !options.quiet) {
        process.stdout.write(`      ${profile.id}: ${removed} instruction(s) dropped\n`);
      }
    }

    const stillHazardous = report.profiles.filter((profile) => findHazards(profile).length > 0);
    process.stdout.write(`\nWritten to ${options.out}\n`);
    if (stillHazardous.length > 0) return 1;
  }

  return 0;
}

main()
  .then((code) => process.exit(code))
  .catch((error: unknown) => {
    process.stderr.write(`voice:import failed: ${String(error)}\n`);
    process.exit(1);
  });
