/**
 * The phrase-ownership report.
 *
 * Ownership is decided by a deterministic default and then reviewed. This
 * renders the review: every phrase more than one rule claims, who ended up with
 * it, who lost it, and whether a curated override was responsible. Writing it to
 * a file is what makes the 76 decisions auditable instead of invisible.
 */

import type { PhraseIndex } from '../dedupe/phrases.js';
import { phraseIndexStats } from '../dedupe/phrases.js';

export interface OwnershipReportOptions {
  readonly generatedAt?: string;
  /** Rules, so the report can show category and phrase count per claimant. */
  readonly ruleMeta?: ReadonlyMap<
    string,
    { readonly category: string; readonly severity: number; readonly phraseCount: number }
  >;
}

export function renderOwnershipReport(
  index: PhraseIndex,
  options: OwnershipReportOptions = {},
): string {
  const stats = phraseIndexStats(index);
  const meta = options.ruleMeta;
  const lines: string[] = [];

  lines.push('# PHRASE_OWNERSHIP');
  lines.push('');
  lines.push('Generated by `npm run phrases:report`. **Do not edit by hand.**');
  lines.push('');
  lines.push('Every watched phrase has exactly one owning rule. The other claimants keep the');
  lines.push('phrase in their data — it is what the upstream said — but do not match on it, so');
  lines.push('one phrase produces one finding rather than one per rule that noticed it.');
  lines.push('');
  lines.push(`Generated: ${options.generatedAt ?? new Date().toISOString()}`);
  lines.push('');
  lines.push('## Summary');
  lines.push('');
  lines.push(`- Distinct matchable phrases: **${stats.distinct}**`);
  lines.push(`- Literal: ${stats.literal} · Template: ${stats.template}`);
  lines.push(`- Contested, claimed by more than one rule: **${stats.contested}**`);
  lines.push(`- Settled by a curated override: **${stats.overridden}**`);
  lines.push(`- Dropped as duplicated within one rule: ${stats.selfDuplicates}`);
  lines.push(`- Findings avoided by ownership: **${stats.findingsAvoided}**`);
  lines.push('');

  const byReason = new Map<string, number>();
  for (const entry of index.contested) {
    byReason.set(entry.reason, (byReason.get(entry.reason) ?? 0) + 1);
  }
  lines.push('### How each decision was reached');
  lines.push('');
  lines.push('| Reason | Count | What it means |');
  lines.push('| --- | ---: | --- |');
  const meanings: Record<string, string> = {
    'sole-claimant': 'Only one rule claims it. No decision was needed.',
    'fewest-phrases': 'Default: the narrower rule won.',
    severity: 'Phrase counts tied, so the more severe rule won.',
    alphabetical: 'Phrase counts and severities tied, so the id broke it.',
    override: 'A curated entry overruled the default. See the table below.',
  };
  for (const [reason, count] of [...byReason].sort((a, b) => b[1] - a[1])) {
    lines.push(`| \`${reason}\` | ${count} | ${meanings[reason] ?? ''} |`);
  }
  lines.push('');

  lines.push('## Every contested phrase');
  lines.push('');
  lines.push('| Phrase | Kind | Owner | Reason | Decided against |');
  lines.push('| --- | --- | --- | --- | --- |');
  for (const entry of index.contested) {
    const phrase = entry.phrase.replace(/\|/g, '\\|');
    lines.push(
      `| \`${phrase}\` | ${entry.kind} | \`${entry.owner}\` | ${entry.reason} | ${entry.others.map((o) => `\`${o}\``).join(', ')} |`,
    );
  }
  lines.push('');

  if (meta) {
    lines.push('## Specificity, which is what the default measures');
    lines.push('');
    lines.push('| Rule | Category | Severity | Matchable phrases |');
    lines.push('| --- | --- | ---: | ---: |');
    for (const [id, info] of [...meta].sort((a, b) => a[1].phraseCount - b[1].phraseCount)) {
      lines.push(`| \`${id}\` | ${info.category} | ${info.severity} | ${info.phraseCount} |`);
    }
    lines.push('');
  }

  lines.push('## Rules that own nothing');
  lines.push('');
  lines.push('A rule with no phrases is not broken: it is detected structurally or');
  lines.push('statistically rather than lexically. Listed so the split is visible.');
  lines.push('');
  if (meta) {
    const silent = [...meta].filter(([, info]) => info.phraseCount === 0).map(([id]) => id);
    for (const id of silent) lines.push(`- \`${id}\``);
    if (silent.length === 0) lines.push('- none');
  }
  lines.push('');

  return `${lines.join('\n')}\n`;
}
